#**Numpy_Hands_On**

*   **Array** is the **homogenous collection of data**.Data can be different types.
*   1D array is called **Series**.
*   2D,3D,4D so on can be called as **Matrix (DataFrame)**.



In [ ]:
import numpy as np

**Q1.Create the 1D numpy array with numpy array module and with a datatype integer and float.**

In [ ]:
arr1 = np.arange(10, dtype = 'int')
arr2 = np.arange(10, dtype = 'float')

In [ ]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

**Q2.Create the numpy array that have zero,one, two, three dimension respectively.Alsoprint the shape and dimensions of the numpy arrays created above.**

In [ ]:
arr0 = np.array(1)  #0 dimension -->only single element present.
arr1 = np.arange(10) #1D array
arr2 = np.arange(9).reshape(3,3)  #2D array
arr3 = np.array([[[1,2,3,4,5]]])  #3D array --> no. of square bracket will define the dimension. Here 3 sq bracket means 3D array.

In [ ]:
arr0

array(1)

In [ ]:
arr1  #1D array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1.shape

(10,)

In [ ]:
arr1.ndim

1

In [ ]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr2.shape

(3, 3)

In [ ]:
arr2.ndim

2

In [ ]:
arr3

array([[[1, 2, 3, 4, 5]]])

In [ ]:
arr3.ndim

3

In [ ]:
#0dimension
print('array 0d:', arr0)
print('shape 0d:' ,arr0.shape)
print('dimension 0d:' ,arr0.ndim)

#1D
print('array 1d:', arr1)
print('shape 1d:' ,arr1.shape)
print('dimension 1d:' ,arr1.ndim)

#2D
print('array 2d:', arr2)
print('shape 2d:' ,arr2.shape)
print('dimension 2d:' ,arr2.ndim)

#3D
print('array 3d:', arr3)
print('shape 3d:' ,arr3.shape)  #(no. of blocks, row in each block,column in each block) (1,1,5)
print('dimension 3d:' ,arr3.ndim)


array 0d: 1
shape 0d: ()
dimension 0d: 0
array 1d: [0 1 2 3 4 5 6 7 8 9]
shape 1d: (10,)
dimension 1d: 1
array 2d: [[0 1 2]
 [3 4 5]
 [6 7 8]]
shape 2d: (3, 3)
dimension 2d: 2
array 3d: [[[1 2 3 4 5]]]
shape 3d: (1, 1, 5)
dimension 3d: 3


**Q3.Create a 2x2, 3x3, 4x4 (rows,columns) identity matrix using Numpy.**

In [ ]:
#np.eye
# np.identity (both does same work)
 #diagonal elements will be 1 and other elements will be 0.

arr1 = np.identity(2)  #2x2
arr2 = np.identity(3)  #3x3
arr3 = np.identity(4)  #4x4

print(arr1)
print(arr2)
print(arr3)

#2nd way: to make an identity matrix with rows != columns: use np.eye
#[1,0,0]
#[0,1,0]

eye2 = np.eye(2)
print(eye2)

eye23 = np.eye(2,3)
print(eye23)

#np.identity(2,3) --> it will through an error.


[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]]


**Q4.Create a numpy array with shape 2x5 that has all the elements as zero.**

In [ ]:
#1st way
zeros = np.zeros((2,5), dtype = 'int') #zeros() has default value is float.
print(zeros)

#2nd way
arr0 = np.full((2,5),0)  #full() has default value is int rather than float.
print(arr0)

#3rd way
arr1 = np.ones((2,5))   #ones() has default valuebis float.
print(arr1*0)

[[0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


**Q5.Create a numpy array that has the shape 3x5 and all the elements are 5.**

In [ ]:
#1st way
arr5 = np.full((3,5),5)
print(arr5)

#2nd way

arr = np.ones((3,5), dtype = 'int')
print(arr*5)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


**Q6.Create a numpy array with random integers in range 0-100 and sample size should be 25.**

In [ ]:
arr = np.random.randint(0,100,25)  #low = 0, high = 100, total element = 25
arr

array([33, 89, 34, 92, 65, 73, 47, 92, 88, 99, 77, 56, 68, 31, 88, 77,  2,
       25, 12, 27, 39,  6, 36, 30, 82])

In [ ]:
random_float = np.random.random(5) # low = 0, high = 1: to fetch 5 float values
random_float

array([0.78910794, 0.01351072, 0.92887199, 0.65786818, 0.84766518])

In [ ]:
arr = np.random.randn(3) # low = -1, high = 1: to fetch 3 values
arr

array([ 1.63093438,  0.56938649, -1.1157741 ])

In [ ]:
linspace_arr = np.linspace(1,25,7) #equi_distance values from each other.
linspace_arr

array([ 1.,  5.,  9., 13., 17., 21., 25.])

In [ ]:
# In arange() last element will not considered.

array = np.arange(0,20,2) #start, end, skip value.
array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

**Q7.Create a numpy array with a shape 3x3 that has all the elements as 1.**

In [ ]:
array_1 = np.ones((3,3))
array_1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Q8.Create a numpy array in the shape 2x3 with random integers in the range 0-100. Reshape the array in the shape 3x2 and print the updated shape of the resultant array.**

In [ ]:
random_arr = np.random.randint(0,100, size = (2,3))
print(random_arr)
print(random_arr.shape)

random_arr = random_arr.reshape((3,2))
print(random_arr)
print(random_arr.shape)

[[95 82 51]
 [96 21 65]]
(2, 3)
[[95 82]
 [51 96]
 [21 65]]
(3, 2)


**Q9.Create a random array with the range 0-1000 with a size = 50.Step 2: Perform the following operations on the same.**

**a.Print the first 10 elements in the array**

**b.Print the last 10 elements of the array**

**c.Print the elements from the indexes 10-25**

**d.Print the element at the index 22**

**e.Print the array using negative indexing**

**f.Print the last 10 elements of the array, using negative indexing**

In [ ]:
random_arr = np.random.randint(0,1000,2)
print(random_arr)
arr = np.random.choice(arr,50)  #choice()--> working as random.randint()
print(arr)

[829 326]
[ 1.63093438  0.56938649 -1.1157741   1.63093438 -1.1157741   0.56938649
  0.56938649  0.56938649  0.56938649  0.56938649 -1.1157741   1.63093438
 -1.1157741  -1.1157741   0.56938649  0.56938649 -1.1157741   1.63093438
  0.56938649 -1.1157741  -1.1157741   0.56938649  0.56938649  1.63093438
 -1.1157741   0.56938649 -1.1157741  -1.1157741  -1.1157741   1.63093438
  1.63093438  1.63093438 -1.1157741  -1.1157741   1.63093438 -1.1157741
  1.63093438  0.56938649 -1.1157741   0.56938649  1.63093438  0.56938649
  1.63093438  1.63093438  0.56938649 -1.1157741   1.63093438  1.63093438
  0.56938649  1.63093438]


In [ ]:
#(a)

arr[0:10]

array([ 1.63093438,  0.56938649, -1.1157741 ,  1.63093438, -1.1157741 ,
        0.56938649,  0.56938649,  0.56938649,  0.56938649,  0.56938649])

In [ ]:
#(b)

arr[-10:]

array([ 1.63093438,  0.56938649,  1.63093438,  1.63093438,  0.56938649,
       -1.1157741 ,  1.63093438,  1.63093438,  0.56938649,  1.63093438])

In [ ]:
#(c)

arr[10:25]

array([-1.1157741 ,  1.63093438, -1.1157741 , -1.1157741 ,  0.56938649,
        0.56938649, -1.1157741 ,  1.63093438,  0.56938649, -1.1157741 ,
       -1.1157741 ,  0.56938649,  0.56938649,  1.63093438, -1.1157741 ])

In [ ]:
#(d)
arr[22]

0.5693864879487002

In [ ]:
#(e)
arr[-1]

1.6309343752582521

In [ ]:
#(f)

arr[-10:]

array([ 1.63093438,  0.56938649,  1.63093438,  1.63093438,  0.56938649,
       -1.1157741 ,  1.63093438,  1.63093438,  0.56938649,  1.63093438])

In [ ]:
#reverse the array

arr[::-1]

array([ 1.63093438,  0.56938649,  1.63093438,  1.63093438, -1.1157741 ,
        0.56938649,  1.63093438,  1.63093438,  0.56938649,  1.63093438,
        0.56938649, -1.1157741 ,  0.56938649,  1.63093438, -1.1157741 ,
        1.63093438, -1.1157741 , -1.1157741 ,  1.63093438,  1.63093438,
        1.63093438, -1.1157741 , -1.1157741 , -1.1157741 ,  0.56938649,
       -1.1157741 ,  1.63093438,  0.56938649,  0.56938649, -1.1157741 ,
       -1.1157741 ,  0.56938649,  1.63093438, -1.1157741 ,  0.56938649,
        0.56938649, -1.1157741 , -1.1157741 ,  1.63093438, -1.1157741 ,
        0.56938649,  0.56938649,  0.56938649,  0.56938649,  0.56938649,
       -1.1157741 ,  1.63093438, -1.1157741 ,  0.56938649,  1.63093438])

**Q10.Give the numpy array that has values = [1,2,3,4,5]**

**Perform the following operations**

**(a).Insert the element 6 at the end of the array.**

**(b). Insert the element 10 at the beginning of the array**

**(c).Insert the element 30, before 4.**

**(d).Update the element 5 as 50**

**(e).Delete the element 50 in the updated array**

**(f).Create a function to search for the element 30.**

**(g).Sort the array in ascending order.**

In [42]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [43]:
#(a)

#arr = list(arr)
#arr

arr = np.append(arr,6)
print(arr)


[1 2 3 4 5 6]


In [45]:
#(b)

#arr.insert(0,10) #insert(index position,value)
#arr

arr = np.insert(arr,0,10)
arr

array([10,  1,  2,  3,  4,  5,  6])

In [47]:
#(c)

#arr.insert(4,30)  #insert(index position, value)
#arr

arr = np.insert(arr,4,30)
arr

array([10,  1,  2,  3, 30,  4,  5,  6])

In [48]:
#(d)

arr[-2] = 50
arr



array([10,  1,  2,  3, 30,  4, 50,  6])

In [ ]:
#(e)

del arr[-2]
arr

#arr = np.delete(arr, index_position)
#arr

#2nd way
# arr.remove(index position)

#3rd way
# arr.pop(index position)

[10, 1, 2, 3, 30, 4, 6]

In [59]:
#(f)..Create a function to search for the element 30.

#membership operator

i = 30
i in arr

#2nd way:

def check(i):
  return i in arr

print(check(30))

True


In [60]:
#(g)

arr.sort()  #ascending order
arr

#arr = np.sort(arr)
#print(arr)

array([ 1,  2,  3,  4,  6, 10, 30, 50])